const cfg=window.APP_CONFIG;
const sb=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);
let session=null,profile=null,rows=[],pdfSolicitudId=null;
const $=id=>document.getElementById(id);
const cop=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n||0);
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const canEdit=()=>['admin','operador'].includes(profile?.role);
const isAdmin=()=>profile?.role==='admin';

async function init(){const {data}=await sb.auth.getSession();if(data.session)await enter(data.session)}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginMsg').textContent='Ingresando...';const {data,error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error)return $('loginMsg').textContent=error.message;await enter(data.session)};
async function enter(s){session=s;const {data,error}=await sb.from('profiles').select('*').eq('id',s.user.id).single();if(error)return alert('No fue posible cargar el perfil. Ejecuta setup.sql y crea el perfil.');profile=data;$('login').classList.add('hidden');$('app').classList.remove('hidden');$('usuario').textContent=`${s.user.email} · ${profile.role}`;await load()}
$('salir').onclick=async()=>{await sb.auth.signOut();location.reload()};

async function upload(files,requestId,tipo){const paths=[];for(const f of files){if(f.size>4000000)throw new Error(`${f.name} supera 4 MB`);const clean=f.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${requestId}/${tipo}/${crypto.randomUUID()}-${clean}`;const {error}=await sb.storage.from('mantenimiento').upload(path,f,{contentType:f.type});if(error)throw error;paths.push({path,tipo,nombre:f.name})}return paths}
$('solForm').onsubmit=async e=>{e.preventDefault();try{$('formMsg').textContent='Guardando...';const id=crypto.randomUUID();const antes=await upload([...$('fotosAntes').files],id,'antes');const despues=await upload([...$('fotosDespues').files],id,'despues');const payload={id,solicitante:$('solicitante').value,ubicacion:$('ubicacion').value,descripcion:$('descripcion').value,prioridad:$('prioridad').value,estado:$('estado').value,fecha_ejecucion:$('fechaEjecucion').value||null,contratista:$('contratista').value,costo:Number($('costo').value||0),observaciones:$('observaciones').value,created_by:session.user.id};const {error}=await sb.from('solicitudes').insert(payload);if(error)throw error;const evidencias=[...antes,...despues];if(evidencias.length){const {error:e2}=await sb.from('evidencias').insert(evidencias.map(x=>({solicitud_id:id,...x,created_by:session.user.id})));if(e2)throw e2}e.target.reset();$('formMsg').textContent='Solicitud guardada correctamente.';await load()}catch(err){$('formMsg').textContent='Error: '+err.message}};

async function load(){const {data,error}=await sb.from('solicitudes').select('*,evidencias(*)').order('created_at',{ascending:false});if(error)return alert(error.message);rows=data||[];render()}
function render(){const q=$('buscar').value.toLowerCase(),f=$('filtro').value;const visible=rows.filter(x=>(!f||x.estado===f)&&JSON.stringify(x).toLowerCase().includes(q));$('stTotal').textContent=rows.length;$('stPend').textContent=rows.filter(x=>x.estado==='Pendiente').length;$('stEjec').textContent=rows.filter(x=>x.estado==='Ejecutada').length;$('stCosto').textContent=cop(rows.reduce((s,x)=>s+Number(x.costo),0));$('lista').innerHTML=visible.map(x=>`<div class="row"><div><h3>${esc(x.codigo)} · ${esc(x.descripcion)}</h3><span class="tag">${esc(x.estado)}</span> <span class="tag">${esc(x.prioridad)}</span><p>${esc(x.ubicacion)} · ${new Date(x.created_at).toLocaleDateString('es-CO')}</p></div><b>${cop(x.costo)}</b><span>${x.fecha_ejecucion||'Sin ejecutar'}</span><div class="smallActions"><button onclick="detail('${x.id}')">Ver / reporte</button>${canEdit()?`<button class="ok" onclick="editRequest('${x.id}')">Editar</button>`:''}</div></div>`).join('')}
$('buscar').oninput=render;$('filtro').onchange=render;

async function signed(path){const {data,error}=await sb.storage.from('mantenimiento').createSignedUrl(path,3600);if(error)throw error;return data.signedUrl}
async function detail(id){const x=rows.find(r=>r.id===id);if(!x)return alert('Solicitud no encontrada.');const ev=await Promise.all((x.evidencias||[]).map(async e=>({...e,url:await signed(e.path)})));window.current={...x,evidencias:ev};pdfSolicitudId=null;const enabled=x.estado==='Ejecutada'||x.estado==='Archivada';$('detalle').innerHTML=`<h2>${esc(x.codigo)}</h2><p><b>${esc(x.descripcion)}</b></p><p>Ubicación: ${esc(x.ubicacion)}<br>Estado: ${esc(x.estado)}<br>Fecha ejecución: ${x.fecha_ejecucion||'No registrada'}<br>Contratista: ${esc(x.contratista)}<br>Coste: ${cop(x.costo)}</p><p>${esc(x.observaciones)}</p>${canEdit()?`<div class="reportActions"><button class="ok" onclick="editRequest('${x.id}')">Editar solicitud</button><button onclick="changeStatus('${x.id}')">Cambiar estado</button></div>`:''}<h3>Fotos antes</h3><div class="gallery">${ev.filter(e=>e.tipo==='antes').map(e=>`<img src="${e.url}" alt="Foto antes">`).join('')||'Sin fotos'}</div><h3>Fotos después</h3><div class="gallery">${ev.filter(e=>e.tipo==='despues').map(e=>`<img src="${e.url}" alt="Foto después">`).join('')||'Sin fotos'}</div>${enabled?`<div class="reportActions"><button onclick="downloadPDF()">Descargar PDF</button>${isAdmin()?`<button class="danger" onclick="removeRequest('${x.id}')">Eliminar definitivamente</button>`:''}</div>${isAdmin()?'<p class="notice">Para eliminar, primero debe descargar el PDF de esta solicitud.</p>':''}`:'<p class="notice">El informe se habilita cuando el estado sea Ejecutada o Archivada.</p>'}`;$('modal').classList.remove('hidden')}
$('cerrarModal').onclick=()=>$('modal').classList.add('hidden');

async function editRequest(id){if(!canEdit())return alert('Acceso denegado.');const x=rows.find(r=>r.id===id);if(!x)return alert('Solicitud no encontrada.');const solicitante=prompt('Solicitante:',x.solicitante||'');if(solicitante===null)return;const ubicacion=prompt('Ubicación / zona:',x.ubicacion||'');if(ubicacion===null||!ubicacion.trim())return alert('La ubicación es obligatoria.');const descripcion=prompt('Descripción:',x.descripcion||'');if(descripcion===null||!descripcion.trim())return alert('La descripción es obligatoria.');const prioridad=prompt('Prioridad: Baja, Media, Alta o Urgente',x.prioridad||'Media');if(prioridad===null)return;if(!['Baja','Media','Alta','Urgente'].includes(prioridad))return alert('Prioridad no válida.');const fecha=prompt('Fecha de ejecución (AAAA-MM-DD) o vacío:',x.fecha_ejecucion||'');if(fecha===null)return;const contratista=prompt('Contratista:',x.contratista||'');if(contratista===null)return;const costoTexto=prompt('Coste final COP:',String(x.costo||0));if(costoTexto===null)return;const costo=Number(costoTexto);if(!Number.isFinite(costo)||costo<0)return alert('Coste no válido.');const observaciones=prompt('Observaciones:',x.observaciones||'');if(observaciones===null)return;const {error}=await sb.from('solicitudes').update({solicitante,ubicacion:ubicacion.trim(),descripcion:descripcion.trim(),prioridad,fecha_ejecucion:fecha.trim()||null,contratista,costo,observaciones}).eq('id',id);if(error)return alert(error.message);pdfSolicitudId=null;await load();$('modal').classList.add('hidden');alert('Solicitud actualizada correctamente.')}
async function changeStatus(id){if(!canEdit())return alert('Acceso denegado.');const x=rows.find(r=>r.id===id);if(!x)return alert('Solicitud no encontrada.');const estado=prompt('Nuevo estado:\nPendiente\nProgramada\nEn ejecución\nEjecutada\nArchivada',x.estado);if(estado===null)return;if(!['Pendiente','Programada','En ejecución','Ejecutada','Archivada'].includes(estado))return alert('Estado no válido. Escríbalo exactamente como aparece en la lista.');const changes={estado};if(estado==='Ejecutada'&&!x.fecha_ejecucion)changes.fecha_ejecucion=new Date().toISOString().slice(0,10);const {error}=await sb.from('solicitudes').update(changes).eq('id',id);if(error)return alert(error.message);pdfSolicitudId=null;await load();await detail(id);alert('Estado actualizado correctamente.')}

async function imageToDataUrl(url){const r=await fetch(url);if(!r.ok)throw new Error('No se pudo cargar una imagen.');const blob=await r.blob();return new Promise((ok,fail)=>{const fr=new FileReader();fr.onload=()=>ok(fr.result);fr.onerror=fail;fr.readAsDataURL(blob)})}
async function makePDF(){const x=window.current;if(!x)throw new Error('No hay una solicitud abierta.');const {jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(18);doc.text('Informe de cierre de mantenimiento',15,18);doc.setFontSize(10);let y=30;for(const line of [`Código: ${x.codigo}`,`Ubicación: ${x.ubicacion}`,`Descripción: ${x.descripcion}`,`Estado: ${x.estado}`,`Fecha de ejecución: ${x.fecha_ejecucion||''}`,`Contratista: ${x.contratista||''}`,`Coste: ${cop(x.costo)}`,`Observaciones: ${x.observaciones||''}`]){const parts=doc.splitTextToSize(line,180);doc.text(parts,15,y);y+=parts.length*6}for(const tipo of ['antes','despues']){doc.addPage();doc.setFontSize(15);doc.text(`Fotografías ${tipo}`,15,18);let iy=28;const imgs=x.evidencias.filter(e=>e.tipo===tipo);if(!imgs.length){doc.setFontSize(10);doc.text('Sin fotografías',15,iy);continue}for(const e of imgs){try{const data=await imageToDataUrl(e.url);const format=data.startsWith('data:image/png')?'PNG':'JPEG';if(iy>220){doc.addPage();iy=20}doc.addImage(data,format,15,iy,80,60);iy+=68}catch{doc.setFontSize(9);doc.text(`No fue posible incluir: ${e.nombre||'imagen'}`,15,iy);iy+=8}}}return doc}
async function downloadPDF(){try{const doc=await makePDF();doc.save(`informe-${window.current.codigo}.pdf`);pdfSolicitudId=window.current.id;alert('PDF descargado. Ya puede eliminar esta solicitud si lo necesita.')}catch(error){alert(`No se pudo generar el PDF: ${error.message}`)}}
async function removeRequest(id){if(!isAdmin())return alert('Acceso denegado.');if(pdfSolicitudId!==id)return alert('Antes de eliminar debe descargar el PDF de esta misma solicitud.');const x=rows.find(r=>r.id===id);if(!x)return alert('Solicitud no encontrada.');if(prompt('Escribe ELIMINAR para borrar definitivamente la solicitud y sus fotos:')!=='ELIMINAR')return;const paths=(x.evidencias||[]).map(e=>e.path);if(paths.length){const {error}=await sb.storage.from('mantenimiento').remove(paths);if(error)return alert(error.message)}const {error}=await sb.from('solicitudes').delete().eq('id',id);if(error)return alert(error.message);pdfSolicitudId=null;$('modal').classList.add('hidden');await load();alert('Solicitud, evidencias y fotografías eliminadas correctamente.')}

$('excel').onclick=()=>{const data=rows.map(({evidencias,...x})=>({...x,fotos:evidencias?.length||0}));const ws=XLSX.utils.json_to_sheet(data),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Solicitudes');XLSX.writeFile(wb,'solicitudes-mantenimiento.xlsx')};
window.detail=detail;window.editRequest=editRequest;window.changeStatus=changeStatus;window.removeRequest=removeRequest;window.downloadPDF=downloadPDF;
init();
