const cfg=window.APP_CONFIG;const sb=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);let session=null,profile=null,rows=[];const $=x=>document.getElementById(x),cop=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n||0),esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function init(){const {data}=await sb.auth.getSession();if(data.session)await enter(data.session)}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginMsg').textContent='Ingresando...';const {data,error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error)return $('loginMsg').textContent=error.message;await enter(data.session)};
async function enter(s){session=s;const {data,error}=await sb.from('profiles').select('*').eq('id',s.user.id).single();if(error)return alert('No fue posible cargar el perfil. Ejecuta setup.sql y crea el perfil.');profile=data;$('login').classList.add('hidden');$('app').classList.remove('hidden');$('usuario').textContent=`${s.user.email} · ${profile.role}`;await load()}
$('salir').onclick=async()=>{await sb.auth.signOut();location.reload()};
async function upload(files,requestId,tipo){const paths=[];for(const f of files){if(f.size>4000000)throw new Error(`${f.name} supera 4 MB`);const clean=f.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${requestId}/${tipo}/${crypto.randomUUID()}-${clean}`;const {error}=await sb.storage.from('mantenimiento').upload(path,f,{contentType:f.type});if(error)throw error;paths.push({path,tipo,nombre:f.name})}return paths}
$('solForm').onsubmit=async e=>{e.preventDefault();try{$('formMsg').textContent='Guardando...';const id=crypto.randomUUID();const antes=await upload([...$('fotosAntes').files],id,'antes');const despues=await upload([...$('fotosDespues').files],id,'despues');const payload={id,solicitante:$('solicitante').value,ubicacion:$('ubicacion').value,descripcion:$('descripcion').value,prioridad:$('prioridad').value,estado:$('estado').value,fecha_ejecucion:$('fechaEjecucion').value||null,contratista:$('contratista').value,costo:Number($('costo').value||0),observaciones:$('observaciones').value,created_by:session.user.id};const {error}=await sb.from('solicitudes').insert(payload);if(error)throw error;if([...antes,...despues].length){const {error:e2}=await sb.from('evidencias').insert([...antes,...despues].map(x=>({solicitud_id:id,...x,created_by:session.user.id})));if(e2)throw e2}e.target.reset();$('formMsg').textContent='Solicitud guardada correctamente.';await load()}catch(err){$('formMsg').textContent='Error: '+err.message}}
async function load(){const {data,error}=await sb.from('solicitudes').select('*,evidencias(*)').order('created_at',{ascending:false});if(error)return alert(error.message);rows=data||[];render()}
function render(){const q=$('buscar').value.toLowerCase(),f=$('filtro').value;const visible=rows.filter(x=>(!f||x.estado===f)&&JSON.stringify(x).toLowerCase().includes(q));$('stTotal').textContent=rows.length;$('stPend').textContent=rows.filter(x=>x.estado==='Pendiente').length;$('stEjec').textContent=rows.filter(x=>x.estado==='Ejecutada').length;$('stCosto').textContent=cop(rows.reduce((s,x)=>s+Number(x.costo),0));$('lista').innerHTML=visible.map(x=>`<div class="row"><div><h3>${esc(x.codigo)} · ${esc(x.descripcion)}</h3><span class="tag">${esc(x.estado)}</span> <span class="tag">${esc(x.prioridad)}</span><p>${esc(x.ubicacion)} · ${new Date(x.created_at).toLocaleDateString('es-CO')}</p></div><b>${cop(x.costo)}</b><span>${x.fecha_ejecucion||'Sin ejecutar'}</span><div class="smallActions"><button onclick="detail('${x.id}')">Ver / reporte</button>${profile.role==='admin'?`<button class="danger" onclick="removeRequest('${x.id}')">Eliminar</button>`:''}</div></div>`).join('')}
$('buscar').oninput=render;$('filtro').onchange=render;
async function signed(path){const {data,error}=await sb.storage.from('mantenimiento').createSignedUrl(path,3600);if(error)throw error;return data.signedUrl}
async function detail(id){const x=rows.find(r=>r.id===id),ev=await Promise.all((x.evidencias||[]).map(async e=>({...e,url:await signed(e.path)})));window.current={...x,evidencias:ev};$('detalle').innerHTML=`<h2>${esc(x.codigo)}</h2><p><b>${esc(x.descripcion)}</b></p><p>Ubicación: ${esc(x.ubicacion)}<br>Estado: ${esc(x.estado)}<br>Fecha ejecución: ${x.fecha_ejecucion||'No registrada'}<br>Contratista: ${esc(x.contratista)}<br>Coste: ${cop(x.costo)}</p><p>${esc(x.observaciones)}</p><h3>Fotos antes</h3><div class="gallery">${ev.filter(e=>e.tipo==='antes').map(e=>`<img src="${e.url}">`).join('')||'Sin fotos'}</div><h3>Fotos después</h3><div class="gallery">${ev.filter(e=>e.tipo==='despues').map(e=>`<img src="${e.url}">`).join('')||'Sin fotos'}</div>${x.estado==='Ejecutada'||x.estado==='Archivada'?`<div class="reportActions"><button onclick="downloadPDF()">Descargar PDF</button><button class="ok" onclick="emailPDF()">Enviar PDF por correo</button>${profile.role==='admin'?`<button class="danger" onclick="removeRequest('${x.id}')">Eliminar definitivamente</button>`:''}</div>`:'<p class="notice">El informe se habilita cuando el estado sea Ejecutada o Archivada.</p>'}`;$('modal').classList.remove('hidden')}
$('cerrarModal').onclick=()=>$('modal').classList.add('hidden');
async function makePDF(){const x=window.current,{jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(18);doc.text('Informe de cierre de mantenimiento',15,18);doc.setFontSize(10);let y=30;const lines=[`Código: ${x.codigo}`,`Ubicación: ${x.ubicacion}`,`Descripción: ${x.descripcion}`,`Estado: ${x.estado}`,`Fecha de ejecución: ${x.fecha_ejecucion||''}`,`Contratista: ${x.contratista||''}`,`Coste: ${cop(x.costo)}`,`Observaciones: ${x.observaciones||''}`];for(const line of lines){const parts=doc.splitTextToSize(line,180);doc.text(parts,15,y);y+=parts.length*6}for(const tipo of ['antes','despues']){doc.addPage();doc.setFontSize(15);doc.text(`Fotografías ${tipo}`,15,18);let iy=28;for(const e of x.evidencias.filter(v=>v.tipo===tipo)){try{const b=await fetch(e.url).then(r=>r.blob()),data=await new Promise(ok=>{const fr=new FileReader();fr.onload=()=>ok(fr.result);fr.readAsDataURL(b)});doc.addImage(data,'JPEG',15,iy,80,60);iy+=68;if(iy>230){doc.addPage();iy=20}}catch{}}}return doc}
async function downloadPDF(){const doc=await makePDF();doc.save(`informe-${window.current.codigo}.pdf`)}
async function emailPDF(){const to=prompt('Correo destinatario:');if(!to)return;const doc=await makePDF(),base64=doc.output('datauristring').split(',')[1];const res=await fetch('/.netlify/functions/send-report',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`},body:JSON.stringify({to,codigo:window.current.codigo,pdfBase64:base64})});const out=await res.json();alert(res.ok?'Informe enviado correctamente.':'Error: '+(out.error||'No se pudo enviar.'))}
async function removeRequest(id){if(profile.role!=='admin')return alert('Acceso denegado.');if(prompt('Escribe ELIMINAR para borrar definitivamente la solicitud y sus fotos:')!=='ELIMINAR')return;const x=rows.find(r=>r.id===id),paths=(x.evidencias||[]).map(e=>e.path);if(paths.length){const {error}=await sb.storage.from('mantenimiento').remove(paths);if(error)return alert(error.message)}const {error}=await sb.from('solicitudes').delete().eq('id',id);if(error)return alert(error.message);$('modal').classList.add('hidden');await load()}
$('excel').onclick=()=>{const data=rows.map(({evidencias,...x})=>({...x,fotos:evidencias?.length||0}));const ws=XLSX.utils.json_to_sheet(data),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Solicitudes');XLSX.writeFile(wb,'solicitudes-mantenimiento.xlsx')};window.detail=detail;window.removeRequest=removeRequest;window.downloadPDF=downloadPDF;window.emailPDF=emailPDF;init();
